## jupyter notebook is one of the IDE - Integreted Development Environment - where we write code

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [8]:
df.isna().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [11]:
df.isna().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [14]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ' , '_')

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [19]:
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [20]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [21]:
# we can categorized the age column 
labled = ['young','adult','middle','senior']
df['age_group'] = pd.qcut(df['age'] ,q = 4 , labels = labled)

In [23]:
df[['age','age_group']].head(10)

   age age_group
0   55    middle
1   19     young
2   50    middle
3   21     young
4   45    middle
5   46    middle
6   63    senior
7   27     young
8   26     young
9   57    middle

In [35]:
frequency_mapping = {
    'Fortnightly' : 14 ,
    'Weekly' : 7 ,
    'Monthly' : 30 ,
    'Quarterly' : 90 ,
    'Bi-Weekly' : 14 ,
    'Annually' : 365 ,
    'Every 3 Months' : 90 
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [36]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,middle,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,young,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,middle,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,young,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,middle,365

In [38]:
df[['discount_applied' , 'promo_code_used']].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [42]:
# At first glance the above columns look like same so it both are same we can remove one to avoid redundancy
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

# as both are same  so one will be dropped

In [43]:
df = df.drop('promo_code_used' , axis = 1)

In [44]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [46]:
df.shape

(3900, 19)

In [47]:
pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp313-cp313-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ----- ---------------------------------- 2.6/17.7 MB 22.6 MB/s eta 0:00:01
   -------- ------------------------------- 3.7/17.7 MB 22.2 MB/s eta 0:00:01
   ------------ --------------------------- 5.5/17.7 MB 9.5 MB/s eta 0:00:02
   ------------- -------------------------- 6.0/17.7 MB 7.5 MB/s eta 0:00:02
   --------------- ------------------------ 6.8/17.7 MB 6.8 MB/s eta 0:00:02
   ----------------- ---------------------- 7.6/17.7 MB 6.4 MB/s eta 0:00:02
   -------------------- ------------------- 8.9/17.7 MB 6.2 MB/s eta 0:00:02
   ---------------------- ----------------- 10.0/17.7 MB 6.0 MB/s eta 0:00:02
   ------------------------ --------------- 10.7/17.7 MB 5.8 MB/s eta 0:00:02
   --------------------------- ------------ 12.1/17.7 MB 5.8 MB/s eta 0:00:01
   ----------------------------- ---------- 13.1/17.7 MB 5.7 MB/s eta 0:00:01
   ------------------------------- -------- 13.9/17.7 MB 5.6 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 5.4 MB/s eta 0:00:01
   ---------------------------------- ----- 15.5/17.7 MB 5.2 MB/s eta 0:00:01
   ------------------------------------- -- 16.8/17.7 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 5.2 MB/s  0:00:03
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

In [48]:
import mysql.connector
cnx = mysql.connector.connect(
    user = 'root' ,
password = 'Neha@roy12345',
host = 'localhost' ,
port = 3306 ,
database = 'customer_behavior_analysis'
)
if cnx.is_connected():
    print('connected to the customer_behavior_analysis ✅')

connected to the customer_behavior_analysis ✅

In [49]:
cur = cnx.cursor(buffered = True)
cur.execute('Drop table if exists students ')

In [53]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\abcom\anaconda4\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\abcom\anaconda4\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\abcom\anaconda4\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [60]:
import urllib.parse
import pandas as pd
from sqlalchemy import create_engine

# 1. Properly encode the password containing the '@' symbol
password = urllib.parse.quote_plus("Neha@roy12345")

# 2. Use the 'password' variable inside the f-string (notice {password} instead of the raw text)
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/customer_behavior_analysis")

# 3. Write DataFrame to MySQL
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

# 4. Read back a sample to verify it worked
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle,365